In [2]:
#Task: Restaurant Recommendation

Objective: Create a restaurant recommendation
system based on user preferences.
Steps:


Preprocess the dataset by handling missing
values and encoding categorical variables.
Determine the criteria for restaurant
recommendations (e.g., cuisine preference,
price range).


Implement a content-based filtering
approach where users are recommended
restaurants similar to their preferred criteria.


Test the recommendation system by
providing sample user preferences and
evaluating the quality of recommendations.

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('D:\Datasets/intern.csv')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
#DATA SET INFORMATION

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [34]:
#CHECKING IF THJERE ARE ANY NULL VALUES/ MISSING VALUES

In [4]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [5]:
df = df.dropna()
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [6]:
df.describe()

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.542000e+03,9542.000000,9542.000000,9542.000000,9542.000000,9542.000000,9542.000000,9542.000000
mean,9.043301e+06,18.179208,64.274997,25.848532,1200.326137,1.804968,2.665238,156.772060
std,8.791967e+06,56.451600,41.197602,11.010094,16128.743876,0.905563,1.516588,430.203324
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019312e+05,1.000000,77.081565,28.478658,250.000000,1.000000,2.500000,5.000000
50%,6.002726e+06,1.000000,77.192031,28.570444,400.000000,2.000000,3.200000,31.000000
75%,1.835260e+07,1.000000,77.282043,28.642711,700.000000,2.000000,3.700000,130.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [7]:
#let us take a sample from the population(dataset)

df.sample()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
7658,9116,Arora Pastry Palace,1,New Delhi,"Dwarka Mod Metro Station, Pillar Number 781, U...",Uttam Nagar,"Uttam Nagar, New Delhi",77.032485,28.619143,"Bakery, Fast Food",...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,3

In [8]:
df.sample()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
6832,18485984,CHA! WA!!,1,New Delhi,"111, Chaudhary Hukum Chand Marg, Humayuour, Sa...",Safdarjung,"Safdarjung, New Delhi",0.0,0.0,"Fast Food, Beverages, Desserts",...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,1

In [9]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
df['Switch to order menu'] = labelencoder.fit_transform(df['Switch to order menu'])
df['Has Table booking'] = labelencoder.fit_transform(df['Has Table booking'])
df['Has Online delivery'] = labelencoder.fit_transform(df['Has Online delivery'])
df['Is delivering now'] = labelencoder.fit_transform(df['Is delivering now'])
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),1,0,0,0,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),1,0,0,0,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),1,0,0,0,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),0,0,0,0,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),1,0,0,0,4,4.8,Dark Green,Excellent,229

In [10]:
#ORDINAL ENCODING FOR RATING COLOR COLUMN

from sklearn.preprocessing import OrdinalEncoder
ordinalencoder = OrdinalEncoder(categories=[['Orange', 'White', 'Yellow','Green','Dark Green','Red']])
df['Rating color'] = ordinalencoder.fit_transform(df[['Rating color']])
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),1,0,0,0,3,4.8,4.0,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),1,0,0,0,3,4.5,4.0,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),1,0,0,0,4,4.4,3.0,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),0,0,0,0,4,4.9,4.0,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),1,0,0,0,4,4.8,4.0,Excellent,229

In [11]:
#ORDINAL ENCODING FOR RATING TEXT COLUMN
ordinalencoder = OrdinalEncoder(categories=[['Not rated','Poor','Average','Good','Very Good','Excellent']])
df['Rating text'] = ordinalencoder.fit_transform(df[['Rating text']])
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),1,0,0,0,3,4.8,4.0,5.0,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),1,0,0,0,3,4.5,4.0,5.0,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),1,0,0,0,4,4.4,3.0,4.0,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),0,0,0,0,4,4.9,4.0,5.0,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),1,0,0,0,4,4.8,4.0,5.0,229

In [12]:
#I AM USING MINMAX SCALAR TO SCALE THE VALUES BETWEEN 0 AND 1 (MINMAX NORMALIZATION)

from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
df[['Country Code','Average Cost for two','Price range','Restaurant ID','Longitude','Latitude']] = minmax_scaler.fit_transform(df[['Country Code','Average Cost for two','Price range','Restaurant ID','Longitude','Latitude']])
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,0.341480,Le Petit Souffle,0.748837,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",0.838318,0.574426,"French, Japanese, Desserts",...,Botswana Pula(P),1,0,0,0,0.666667,4.8,4.0,5.0,314
1,0.340758,Izakaya Kikufuji,0.748837,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",0.838278,0.574305,Japanese,...,Botswana Pula(P),1,0,0,0,0.666667,4.5,4.0,5.0,591
2,0.340527,Heat - Edsa Shangri-La,0.748837,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",0.838406,0.574590,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),1,0,0,0,1.000000,4.4,3.0,4.0,270
3,0.341527,Ooma,0.748837,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838405,0.574630,"Japanese, Sushi",...,Botswana Pula(P),0,0,0,0,1.000000,4.9,4.0,5.0,365
4,0.341300,Sambo Kojin,0.748837,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838408,0.574621,"Japanese, Korean",...,Botswana Pula(P),1,0,0,0,1.000000,4.8,4.0,5.0,229

In [13]:
df_dummies = pd.get_dummies(df, columns=['Cuisines'], drop_first=True)
df_dummies.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Average Cost for two,...,"Cuisines_Turkish, Arabian, Middle Eastern","Cuisines_Turkish, Arabian, Moroccan, Lebanese","Cuisines_Turkish, Mediterranean, Middle Eastern",Cuisines_Vietnamese,"Cuisines_Vietnamese, Fish and Chips","Cuisines_Western, Asian, Cafe","Cuisines_Western, Fusion, Fast Food",Cuisines_World Cuisine,"Cuisines_World Cuisine, Mexican, Italian","Cuisines_World Cuisine, Patisserie, Cafe"
0,0.341480,Le Petit Souffle,0.748837,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",0.838318,0.574426,0.001375,...,False,False,False,False,False,False,False,False,False,False
1,0.340758,Izakaya Kikufuji,0.748837,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",0.838278,0.574305,0.001500,...,False,False,False,False,False,False,False,False,False,False
2,0.340527,Heat - Edsa Shangri-La,0.748837,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",0.838406,0.574590,0.005000,...,False,False,False,False,False,False,False,False,False,False
3,0.341527,Ooma,0.748837,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838405,0.574630,0.001875,...,False,False,False,False,False,False,False,False,False,False
4,0.341300,Sambo Kojin,0.748837,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838408,0.574621,0.001875,...,False,False,False,False,False,False,False,False,False,False

In [14]:
df_numeric = df_dummies *1
df_numeric.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Average Cost for two,...,"Cuisines_Turkish, Arabian, Middle Eastern","Cuisines_Turkish, Arabian, Moroccan, Lebanese","Cuisines_Turkish, Mediterranean, Middle Eastern",Cuisines_Vietnamese,"Cuisines_Vietnamese, Fish and Chips","Cuisines_Western, Asian, Cafe","Cuisines_Western, Fusion, Fast Food",Cuisines_World Cuisine,"Cuisines_World Cuisine, Mexican, Italian","Cuisines_World Cuisine, Patisserie, Cafe"
0,0.341480,Le Petit Souffle,0.748837,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",0.838318,0.574426,0.001375,...,0,0,0,0,0,0,0,0,0,0
1,0.340758,Izakaya Kikufuji,0.748837,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",0.838278,0.574305,0.001500,...,0,0,0,0,0,0,0,0,0,0
2,0.340527,Heat - Edsa Shangri-La,0.748837,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",0.838406,0.574590,0.005000,...,0,0,0,0,0,0,0,0,0,0
3,0.341527,Ooma,0.748837,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838405,0.574630,0.001875,...,0,0,0,0,0,0,0,0,0,0
4,0.341300,Sambo Kojin,0.748837,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838408,0.574621,0.001875,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Columns: 1844 entries, Restaurant ID to Cuisines_World Cuisine, Patisserie, Cafe
dtypes: bool(1824), float64(9), int32(4), int64(1), object(6)
memory usage: 18.0+ MB

In [19]:
#CONTENT BASED FILTERING

In [20]:
#defining criteria  and using cosine similarity  for similarity calculation

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

criteria = ["Cuisines_Vietnamese", 'Price range']

criteria_df = df_numeric[criteria]
similarity_matrix = cosine_similarity(criteria_df)

In [17]:
criteria_df

      Cuisines_Vietnamese  Price range
0                       0     0.666667
1                       0     0.666667
2                       0     1.000000
3                       0     1.000000
4                       0     1.000000
...                   ...          ...
9546                    0     0.666667
9547                    0     0.666667
9548                    0     1.000000
9549                    0     1.000000
9550                    0     0.333333

[9542 rows x 2 columns]

In [18]:
similarity_matrix

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [19]:
def get_recommendations(restaurant_index, num_recommendations=5):
    sim_scores = list(enumerate(similarity_matrix[restaurant_index]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_indices = [i[0] for i in sim_scores[1:num_recommendations+1]]

    return df_numeric.iloc[sim_indices]

# Example 
sample_restaurant_index = 1
recommendations = get_recommendations(sample_restaurant_index)
recommendations

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Average Cost for two,...,"Cuisines_Turkish, Arabian, Middle Eastern","Cuisines_Turkish, Arabian, Moroccan, Lebanese","Cuisines_Turkish, Mediterranean, Middle Eastern",Cuisines_Vietnamese,"Cuisines_Vietnamese, Fish and Chips","Cuisines_Western, Asian, Cafe","Cuisines_Western, Fusion, Fast Food",Cuisines_World Cuisine,"Cuisines_World Cuisine, Mexican, Italian","Cuisines_World Cuisine, Patisserie, Cafe"
1,0.340758,Izakaya Kikufuji,0.748837,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",0.838278,0.574305,0.001500,...,0,0,0,0,0,0,0,0,0,0
2,0.340527,Heat - Edsa Shangri-La,0.748837,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",0.838406,0.574590,0.005000,...,0,0,0,0,0,0,0,0,0,0
3,0.341527,Ooma,0.748837,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838405,0.574630,0.001875,...,0,0,0,0,0,0,0,0,0,0
4,0.341300,Sambo Kojin,0.748837,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838408,0.574621,0.001875,...,0,0,0,0,0,0,0,0,0,0
5,0.983175,Din Tai Fung,0.748837,Mandaluyong City,"Ground Floor, Mega Fashion Hall, SM Megamall, ...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838405,0.574614,0.001250,...,0,0,0,0,0,0,0,0,0,0

In [25]:
 #Test the Recommendation System

In [20]:
sample_criteria = {'Cuisines_Vietnamese': 1, 'Price range': 2}
user_df = pd.DataFrame([sample_criteria])
user_similarity = cosine_similarity(user_df, criteria_df)
user_sim_indices = list(enumerate(user_similarity[0]))
user_sim_indices = sorted(user_sim_indices, key=lambda x: x[1], reverse=True)
recommended_restaurants = df_numeric.iloc[[i[0] for i in user_sim_indices[:5]]]

recommended_restaurants

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Average Cost for two,...,"Cuisines_Turkish, Arabian, Middle Eastern","Cuisines_Turkish, Arabian, Moroccan, Lebanese","Cuisines_Turkish, Mediterranean, Middle Eastern",Cuisines_Vietnamese,"Cuisines_Vietnamese, Fish and Chips","Cuisines_Western, Asian, Cafe","Cuisines_Western, Fusion, Fast Food",Cuisines_World Cuisine,"Cuisines_World Cuisine, Mexican, Italian","Cuisines_World Cuisine, Patisserie, Cafe"
0,0.341480,Le Petit Souffle,0.748837,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",0.838318,0.574426,0.001375,...,0,0,0,0,0,0,0,0,0,0
1,0.340758,Izakaya Kikufuji,0.748837,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",0.838278,0.574305,0.001500,...,0,0,0,0,0,0,0,0,0,0
2,0.340527,Heat - Edsa Shangri-La,0.748837,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",0.838406,0.574590,0.005000,...,0,0,0,0,0,0,0,0,0,0
3,0.341527,Ooma,0.748837,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838405,0.574630,0.001875,...,0,0,0,0,0,0,0,0,0,0
4,0.341300,Sambo Kojin,0.748837,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",0.838408,0.574621,0.001875,...,0,0,0,0,0,0,0,0,0,0